server:
  port: 8080

output:
  debug: true
  format: long

pages:
  - domain: cedi.dev

    # Configure the S3 bucket where the website is hosted in
    bucket:
      url: https://s3.eu-central-003.backblazeb2.com
      name: cedi-testing
      applicationId: ENV(APPLICATION_ID)
      secret: ENV(SECRET_NAME)

    # Configure Proxy URL
    proxy:
      url: https://f003.backblazeb2.com
      path: file/cedi-testing/cedi

    # specify a (default) retention period (how many commit websites to keep)
    history: 10

    # Grant access to repositories to use this domain
    allowed:
      # Option 1: allow an entire org
      - https://github.com/SpechtLabs/*

      # Option 2: fine graned control to individual repositories
      - https://github.com/SpechtLabs/spechtlabs.github.io

    # Configure how sub-domains are handed out
    # {{ .Environment }} - the environment as sent by GHA
    # {{ .RepoName }} - the name of the Git repository
    # {{ .Domain }} - the Domain name configured at the top of the page
    subDomains:
      'spechtlabs.github.io':
        # pattern supports go-template
        pattern: '{{ if len(.Environment) gt 0 }} {{ .Environment }}.{{ end }}{{ .Domain }}'
        history: 15                # keep the latest 15 commits (except the 'active' commit)

      '*':
        pattern: '{{ .RepoName }}.{{ .Domain }}'