server:
  proxyPort: 8080
  apiPort: 8081

proxy:
  maxIdleConns: 1000
  maxIdleConnsPerHost: 500
  timeout: 30s
  compression: false

output:
  format: long

pages:
#  - domain: cedi.av0.de
#
#    # Configure the S3 bucket where the website is hosted in
#    bucket:
#      url: https://s3.eu-central-003.backblazeb2.com
#      name: cedi-testing
#      applicationId: ENV(APPLICATION_ID)
#      secret: ENV(S3_SECRET)
#
#    # Configure Proxy URL
#    proxy:
#      url: https://f003.backblazeb2.com
#      path: file/cedi-testing/cedi
#
#    # specify a retention period (how many commit websites to keep)
#    history: 10
#
#    # Grant access to the repositories to use this domain
#    auth:
#      provider: github
#      repository: cedi/cedi.github.io.git
#
#    # Configure how sub-domains are handed out
#    # {{ .Environment }} - the environment as sent by GHA
#    # {{ .RepoName }} - the name of the Git repository
#    # {{ .Domain }} - the Domain name configured at the top of the page
#    subDomains:
#      'spechtlabs.github.io':
#        # pattern supports go-template
#        pattern: '{{ if len(.Environment) gt 0 }} {{ .Environment }}.{{ end }}{{ .Domain }}'
#        history: 15                # keep the latest 15 commits (except the 'active' commit)
#
#      '*':
#        pattern: '{{ .RepoName }}.{{ .Domain }}'

  - domain: gold-specht.av0.de

    # Configure the S3 bucket where the website is hosted in
    bucket:
      region: eu-central-003
      url: https://s3.eu-central-003.backblazeb2.com
      name: cedi-testing
      applicationId: ENV(APPLICATION_ID)
      secret: ENV(S3_SECRET)

    # Configure Proxy URL
    proxy:
      url: https://f003.backblazeb2.com
      path: file/cedi-testing
      notFound: 404.html
      searchPath:
        - /index.html
        - /index.htm

    # Grant access to the repositories to use this domain
    git:
      provider: custom
      repository: Goldschmiede-Metallglanz/Goldschmiede-Metallglanz
      mainBranch: main
      oidc:
        issuer: https://token.actions.githubusercontent.com
        claimMappings:
          Repository: repository
          Commit: sha
          Branch: ref
          Environment: environment

    # Configure preview-build sub domains
    preview:
      enabled: true
      sha: true
      environment: false
      branch: true